<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Importa DB facade

class AsesorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('asesor')->insert([
            [
                'idAsesor' => 2,
                'nombre' => 'Jorge William Figueroa Corzo',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:16:07',
            ],
            [
                'idAsesor' => 3,
                'nombre' => 'Jesús Carlos Sánchez Guzmán',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:16:28',
            ],
            [
                'idAsesor' => 4,
                'nombre' => 'Octavio Ariosto Ríos Tercero',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:16:54',
            ],
            [
                'idAsesor' => 5,
                'nombre' => 'Rosy Ilda Basave Torres',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:17:09',
            ],
            [
                'idAsesor' => 6,
                'nombre' => 'Nestor Antonio Morales Navarro',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:17:25',
            ],
            [
                'idAsesor' => 7,
                'nombre' => 'María Guadalupe Monjaras Velasco',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:17:49',
            ],
            [
                'idAsesor' => 8,
                'nombre' => 'Germán Ríos Toledo',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:18:03',
            ],
            [
                'idAsesor' => 9,
                'nombre' => 'Ciclalli Cabrera García',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:18:26',
            ],
            [
                'idAsesor' => 10,
                'nombre' => 'Francisco de Jesús Suárez Ruíz',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:18:46',
            ],
            [
                'idAsesor' => 11,
                'nombre' => 'Enrique Abel Sánchez Velázquez',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:19:03',
            ],
            [
                'idAsesor' => 12,
                'nombre' => 'Elfer Isaías Clemente Camacho',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:19:18',
            ],
            [
                'idAsesor' => 13,
                'nombre' => 'Miguel Arturo Vázquez Velázquez',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:19:35',
            ],
            [
                'idAsesor' => 14,
                'nombre' => 'Roberto Cruz Gordillo',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-06-01 14:19:47',
            ],
            [
                'idAsesor' => 15,
                'nombre' => 'Walter Torres Roblero',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:31:13',
            ],
            [
                'idAsesor' => 16,
                'nombre' => 'Yaneth Abril Espinoza Corzo',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:31:32',
            ],
            [
                'idAsesor' => 17,
                'nombre' => 'Ruth Madeine Roblero López',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:32:05',
            ],
            [
                'idAsesor' => 18,
                'nombre' => 'Álvaro Hernández Sol',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:32:22',
            ],
            [
                'idAsesor' => 19,
                'nombre' => 'José Humberto Castañón Gonzales',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:36:16',
            ],
            [
                'idAsesor' => 20,
                'nombre' => 'María Leticia Vázquez Ruíz',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:36:47',
            ],
            [
                'idAsesor' => 21,
                'nombre' => 'Alexis de Jesús López Trujillo',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:37:06',
            ],
            [
                'idAsesor' => 22,
                'nombre' => 'Sheyla Karina Flores Guirao',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:37:23',
            ],
            [
                'idAsesor' => 23,
                'nombre' => 'José Armando Fragoso Mandujano',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:37:42',
            ],
            [
                'idAsesor' => 24,
                'nombre' => 'Carlos Alberto Hernández Gutiérrez',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:37:57',
            ],
            [
                'idAsesor' => 25,
                'nombre' => 'Gustavo Méndez Lambarén',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:38:39',
            ],
            [
                'idAsesor' => 26,
                'nombre' => 'Miguel Ángel Lastra Pascacio',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:38:56',
            ],
            [
                'idAsesor' => 27,
                'nombre' => 'Lisandro Gutiérrez Gonzáles',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:39:10',
            ],
            [
                'idAsesor' => 28,
                'nombre' => 'Reiner Rincón Rosales',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:40:24',
            ],
            [
                'idAsesor' => 29,
                'nombre' => 'Eduardo Chandomi Castellanos',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-27 12:40:43',
            ],
            [
                'idAsesor' => 30,
                'nombre' => 'Naghieli De Jesús Pascasio Solorzano',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-28 11:02:54',
            ],
            [
                'idAsesor' => 31,
                'nombre' => 'Jorge Luis Camas Anzueto',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-29 11:01:02',
            ],
            [
                'idAsesor' => 32,
                'nombre' => 'Rubén Grajales Coutiño',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-29 11:01:15',
            ],
            [
                'idAsesor' => 34,
                'nombre' => 'Ildeberto de los Santos Ruíz',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-29 11:02:13',
            ],
            [
                'idAsesor' => 35,
                'nombre' => 'Maria Laura Porraz Ruiz',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:47:39',
            ],
            [
                'idAsesor' => 36,
                'nombre' => 'Adriana Meza León',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:48:00',
            ],
            [
                'idAsesor' => 37,
                'nombre' => 'Jorge Arturo Sarmiento Torres',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:48:11',
            ],
            [
                'idAsesor' => 38,
                'nombre' => 'Liliana Patricia Moreno Cancino',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:48:20',
            ],
            [
                'idAsesor' => 39,
                'nombre' => 'Maria Celina Lujan Hidalgo',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:48:26',
            ],
            [
                'idAsesor' => 40,
                'nombre' => 'Rodrigo Ferrer González',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:48:35',
            ],
            [
                'idAsesor' => 41,
                'nombre' => 'Katty Nallely Fuentes Castro',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:49:06',
            ],
            [
                'idAsesor' => 42,
                'nombre' => 'Romeo Alejandro Velasco La Flor',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:49:12',
            ],
            [
                'idAsesor' => 43,
                'nombre' => 'Jorge Iván Bermúdez Rodríguez',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:49:25',
            ],
            [
                'idAsesor' => 44,
                'nombre' => 'Ana María de la Rosa Flores',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-30 07:49:33',
            ],
            [
                'idAsesor' => 45,
                'nombre' => 'Marco Antonio Zuñiga Reyes',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-31 12:37:59',
            ],
            [
                'idAsesor' => 46,
                'nombre' => 'Juan Humberto Carpio Tovilla',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-31 12:38:08',
            ],
            [
                'idAsesor' => 47,
                'nombre' => 'Gilbert Francis Pérez García',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-08-31 12:38:15',
            ],
            [
                'idAsesor' => 50,
                'nombre' => 'Alfredo Gómez Meoño',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-09-01 11:56:12',
            ],
            [
                'idAsesor' => 51,
                'nombre' => 'Alonso Juarez Ontiveros',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-09-01 11:56:26',
            ],
            [
                'idAsesor' => 52,
                'nombre' => 'Salvador Hernández Garduza',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-09-01 11:56:40',
            ],
            [
                'idAsesor' => 53,
                'nombre' => 'Francisco Ronay López Estrada',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-09-01 11:57:02',
            ],
            [
                'idAsesor' => 55,
                'nombre' => 'Roberto Ibañez Cordova',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-09-01 22:52:09',
            ],
            [
                'idAsesor' => 56,
                'nombre' => 'Tania Carpio Reyes',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-09-01 22:52:39',
            ],
            [
                'idAsesor' => 57,
                'nombre' => 'Rony Obed Suchiapa Díaz',
                'telefono' => '9619876543',
                'correo_electronico' => 'ejemplo@gmail.com',
                'fecha_agregado' => '2024-09-01 22:52:48',
            ],
            [
                'idAsesor' => 58,
                'nombre' => 'Samuel Gómez Peñate',
                'telefono' => '9611111111',
                'correo_electronico' => 'ejemplos@gmail.com',
                'fecha_agregado' => '2024-09-01 22:52:58',
            ],
        ]);
    }
}