<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProyectoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('proyecto')->insert([
            [
                'clave_proyecto' => '0000000000001',
                'nombre' => 'NaturArma',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'NaturArma',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => 'https://www.youtube.com/embed/587RQW2fvwE?si=SL1TaZm48d5vEnJd',
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:50:56',
            ],
            [
                'clave_proyecto' => '0000000000002',
                'nombre' => 'BioGe',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'BioGe',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => 'https://youtu.be/587RQW2fvwEsiYNVlKHiAp15iesuwt1',
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:51:27',
            ],
            [
                'clave_proyecto' => '0000000000003',
                'nombre' => 'BIOPELL',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'BIOPELL',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:51:41',
            ],
            [
                'clave_proyecto' => '0000000000004',
                'nombre' => 'Water Save',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Water Save',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:52:07',
            ],
            [
                'clave_proyecto' => '0000000000005',
                'nombre' => 'Purificador de agua ambiental',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Purificador de agua ambiental',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:54:40',
            ],
            [
                'clave_proyecto' => '0000000000006',
                'nombre' => 'Anisof',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Anisof',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:56:55',
            ],
            [
                'clave_proyecto' => '0000000000007',
                'nombre' => 'EVIE',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'EVIE',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:57:47',
            ],
            [
                'clave_proyecto' => '0000000000008',
                'nombre' => 'Ecokre',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Ecokre',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:58:46',
            ],
            [
                'clave_proyecto' => '0000000000009',
                'nombre' => 'L - UV',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'L UV',
                'categoria' => 12,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-05-30 11:59:36',
            ],
            [
                'clave_proyecto' => '0000000000010',
                'nombre' => 'ARQMX 5000',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'ARQMX 5000',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 14:20:54',
            ],
            [
                'clave_proyecto' => '0000000000011',
                'nombre' => 'SPACE 5000',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'SPACE 5000',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 14:21:27',
            ],
            [
                'clave_proyecto' => '0000000000012',
                'nombre' => 'SEPEMEX',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'SEPEMEX',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 14:21:55',
            ],
            [
                'clave_proyecto' => '0000000000013',
                'nombre' => 'PHYTOBOT',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'PHYTOBOT',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 14:22:31',
            ],
            [
                'clave_proyecto' => '0000000000014',
                'nombre' => 'OptTemp',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'OptTemp',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 14:22:54',
            ],
            [
                'clave_proyecto' => '0000000000015',
                'nombre' => 'Robot Silar',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Robot Silar',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 14:23:12',
            ],
            [
                'clave_proyecto' => '0000000000016',
                'nombre' => 'Tux AuNat',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Tux AuNat',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:09:58',
            ],
            [
                'clave_proyecto' => '0000000000017',
                'nombre' => 'RA - AH',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'RA AH',
                'categoria' => 16,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:16:00',
            ],
            [
                'clave_proyecto' => '0000000000018',
                'nombre' => 'NeuProc',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'NeuProc',
                'categoria' => 16,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:16:24',
            ],
            [
                'clave_proyecto' => '0000000000019',
                'nombre' => 'Snappy',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Snappy',
                'categoria' => 16,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:17:02',
            ],
            [
                'clave_proyecto' => '0000000000020',
                'nombre' => 'SmartFuel',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'SmartFuel',
                'categoria' => 16,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:17:22',
            ],
            [
                'clave_proyecto' => '0000000000021',
                'nombre' => 'DigiTurix',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'DigiTurix',
                'categoria' => 16,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:17:41',
            ],
            [
                'clave_proyecto' => '0000000000022',
                'nombre' => 'T - Rover',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'T Rover',
                'categoria' => 16,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:17:57',
            ],
            [
                'clave_proyecto' => '0000000000023',
                'nombre' => 'Ruta Mexicana',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Ruta Mexicana',
                'categoria' => 15,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:13:10',
            ],
            [
                'clave_proyecto' => '0000000000024',
                'nombre' => 'Raccoon Didactics',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Raccoon Didactics',
                'categoria' => 15,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:13:38',
            ],
            [
                'clave_proyecto' => '0000000000025',
                'nombre' => 'Maestro',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Maestro',
                'categoria' => 15,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:14:03',
            ],
            [
                'clave_proyecto' => '0000000000026',
                'nombre' => 'Culturizatec',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Culturizatec',
                'categoria' => 15,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:14:29',
            ],
            [
                'clave_proyecto' => '0000000000027',
                'nombre' => 'SURCA',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'SURCA',
                'categoria' => 15,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:15:22',
            ],
            [
                'clave_proyecto' => '0000000000028',
                'nombre' => 'VISIONARIA',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'VISIONARIA',
                'categoria' => 15,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:15:40',
            ],
            [
                'clave_proyecto' => '0000000000029',
                'nombre' => 'Balam Selecto',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Balam Selecto',
                'categoria' => 14,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:10:24',
            ],
            [
                'clave_proyecto' => '0000000000030',
                'nombre' => 'Salsa Picante La Brava',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Salsa Picante La Brava',
                'categoria' => 14,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:11:10',
            ],
            [
                'clave_proyecto' => '0000000000031',
                'nombre' => 'Fungi - Tec',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Seed Matic', // Se corrigió el nombre en la descripción
                'categoria' => 14,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:11:35',
            ],
            [
                'clave_proyecto' => '0000000000032',
                'nombre' => 'NixtaFort',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'NixtaFort',
                'categoria' => 14,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:12:34',
            ],
            [
                'clave_proyecto' => '0000000000033',
                'nombre' => 'LOA - AUTOMATIZACION',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'LOA AUTOMATIZACION',
                'categoria' => 14,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:10:47',
            ],
            [
                'clave_proyecto' => '0000000000034',
                'nombre' => 'Seed Matic',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Seed Matic',
                'categoria' => 14,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:12:09',
            ],
            [
                'clave_proyecto' => '0000000000035',
                'nombre' => 'SHIELDmind',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'SHIELDmind',
                'categoria' => 17,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:19:16',
            ],
            [
                'clave_proyecto' => '0000000000036',
                'nombre' => 'Kinetica',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Kinetica',
                'categoria' => 17,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:19:43',
            ],
            [
                'clave_proyecto' => '0000000000037',
                'nombre' => 'TOOP',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'TOOP',
                'categoria' => 17,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:20:12',
            ],
            [
                'clave_proyecto' => '0000000000038',
                'nombre' => 'Justic - IA',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Justic IA',
                'categoria' => 17,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:20:40',
            ],
            [
                'clave_proyecto' => '0000000000039',
                'nombre' => 'EcoVision',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'EcoVision',
                'categoria' => 17,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:21:01',
            ],
            [
                'clave_proyecto' => '0000000000040',
                'nombre' => 'Turix MEWO',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Turix MEWO',
                'categoria' => 17,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:21:20',
            ],
            [
                'clave_proyecto' => '0000000000041',
                'nombre' => 'LanHand',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'LanHand',
                'categoria' => 17,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:18:52',
            ],
            [
                'clave_proyecto' => '0000000000042',
                'nombre' => 'Space Guide',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Space Guide',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:27:58',
            ],
            [
                'clave_proyecto' => '0000000000043',
                'nombre' => 'Turix - AuNaMa',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Turix AuNaMa',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:28:31',
            ],
            [
                'clave_proyecto' => '0000000000044',
                'nombre' => 'SeedMatiC',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'SeedMatiC',
                'categoria' => 14,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:29:09',
            ],
            [
                'clave_proyecto' => '0000000000045',
                'nombre' => 'Pagina web para ventas EG',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Pagina web para ventas de la empresa distribuidora Eléctrica Grijalva',
                'categoria' => 18,
                'tipo' => 13,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:40:31',
            ],
            [
                'clave_proyecto' => '0000000000046',
                'nombre' => 'Sistema de Gestión CO',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Sistema de gestión de miembros del Club Orcas',
                'categoria' => 18,
                'tipo' => 13,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-01 18:45:10',
            ],
            [
                'clave_proyecto' => '0000000000047',
                'nombre' => 'Sistema de Inventario Pemex',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Sistema de inventario de herramientas del área de mantenimiento de Pemex Logística',
                'categoria' => 18,
                'tipo' => 13,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-07 13:35:14',
            ],
            [
                'clave_proyecto' => '0000000000048',
                'nombre' => 'Implementación de tecnologías Didactic Electronic',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Implementación de tecnologías para el desarrollo de mesa didáctica Didactic Electronic',
                'categoria' => 18,
                'tipo' => 13,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-06-07 13:37:00',
            ],
            [
                'clave_proyecto' => '0000000000049',
                'nombre' => 'Phytobot',
                'nombre_descriptivo' => 'Sin asignar',
                'descripcion' => 'Phytobot',
                'categoria' => 13,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2024-08-29 11:04:16',
            ],
            [
                'clave_proyecto' => '0000000000050',
                'nombre' => 'Incubadora',
                'nombre_descriptivo' => 'incuba',
                'descripcion' => 'incuba',
                'categoria' => 18,
                'tipo' => 12,
                'etapa' => 1,
                'video' => null,
                'area_aplicacion' => 'Sin asignar',
                'naturaleza_tecnica' => 'Sin asignar',
                'objetivo' => 'Sin asignar',
                'fecha_agregado' => '2025-06-08 19:26:58',
            ],
        ]);
    }
}